#version: "3.9"

name: nx3

services:
  bb-pinger:
    image: dock01.learn.local:8083/busybox:v1
    command: ping wapp-svc
    depends_on:
      - wapp-svc  

  wapp-svc:
    image: dock01.learn.local:8083/wapp
    #image: dock01:5001/wapp:0.5
    ports:
      - "8060:8080"
    environment:
      - DOCK_HOST=dock03-compose
      - VERSION=1.2

    volumes:
      - wapp:/home/data

#   hostname: wapp1

volumes:
  wapp: {}
 

  
