version: "3.9"


services:
  pinger:
    image: busybox
    command: ping wapp1
    depends_on:
      - wapp1

    environment:
      - VERSION=1.0
      - MAINTAINER=sand
  
  wapp1:
    image: a0z9/dock:wapp.0.5
    ports:
      - "8067:8080"
    environment:
      - DOCK_HOST=DOCK-conf-swarm
    deploy:
      mode: replicated
      replicas: 3    
